"""
Type stubs for exceptions
Auto-generated by AutoPyi on 2025-07-03 21:40:43
"""

def get_error_code(error: int) -> str: ...

# AutoPyi: Low confidence (0.64), please review

def handle_simpleenvs_error(error: int, environment: int) -> str: ...

# AutoPyi: Low confidence (0.64), please review

def is_security_critical(error: int) -> bool: ...

# AutoPyi: Low confidence (0.64), please review

class EnvSecurityError:
    def __init__(self, message: int, details: str) -> None: ...

class FileParsingError:
    def __init__(
        self, file_path: int, line_number: str, original_error: bool
    ) -> None: ...

class FileSizeError:
    def __init__(self, file_path: int, size: str, max_size: bool) -> None: ...

class IntegrityError:
    def __init__(
        self, file_path: int, expected_hash: str, actual_hash: bool
    ) -> None: ...

class InvalidInputError:
    def __init__(self, message: int, input_value: str) -> None: ...

class KeyNotFoundError:
    def __init__(self, key: int, available_keys: str) -> None: ...

class MemorySecurityError:
    def __init__(self, operation: int, reason: str) -> None: ...

class PathTraversalError:
    def __init__(self, path: int) -> None: ...
    # AutoPyi: Low confidence (0.67), please review

class SecureErrorHandler:
    def __init__(self, operation: int, suppress_details: str) -> None: ...

class SessionError:
    def __init__(self, session_id: int, issue: str) -> None: ...

class SimpleEnvsError:
    def __init__(self, message: int, details: str) -> None: ...

class TypeConversionError:
    def __init__(self, key: int, value: str, target_type: bool) -> None: ...

class AccessDeniedError:
    def __init__(self, operation: int, caller: str) -> None: ...

class ConfigurationError:
    def __init__(self, component: int, issue: str) -> None: ...

class EnvNotLoadedError:
    def __init__(self, operation: int) -> None: ...
    # AutoPyi: Low confidence (0.67), please review
